default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: manyo_kadai_development
test:
  <<: *default
  database: manyo_kadai_test
production:
  <<: *default
  database: manyo_kadai_production
  username: manyo_kadai
  password: <%= ENV['MANYO_KADAI_DATABASE_PASSWORD'] %>
